# Generated by Django 4.0.3 on 2022-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='google_link_analyzer',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_key', models.CharField(max_length=90)),
                ('user', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
                ('details', models.TextField()),
                ('web_link', models.CharField(max_length=350)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'google_link_analyzer',
            },
        ),
    ]
